# Generated by Django 3.2.9 on 2021-12-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locality',
            field=models.CharField(default='brussels', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=10000),
        ),
    ]
