# Generated by Django 3.2.9 on 2021-12-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211208_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='superficy',
            field=models.IntegerField(default=100),
        ),
    ]
