# Generated by Django 3.2.9 on 2021-12-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_superficy'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Type_of_property',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='locality',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='superficy',
            field=models.IntegerField(default=''),
        ),
    ]
